Fix MissingReferenceException thrown when saving settings
Prevents an exception with the following stacktrace by adding a try block:
```
MissingReferenceException: The object of type 'GameObject' has been
destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy
the object.
GameMenuController+<CreateButton>c__AnonStorey41.<>m__88 () (at
Assets/Scripts/UI/InGameUI/GameMenu/GameMenuController.cs:80)
ProjectPorcupine.Localization.LocalizationTable.LoadingLanguagesFinished
() (at Assets/Scripts/Localization/LocalizationTable.cs:83)
ProjectPorcupine.Localization.LocalizationLoader.UpdateLocalizationTable
() (at Assets/Scripts/Localization/LocalizationLoader.cs:44)
ProjectPorcupine.Localization.LocalizationLoader.<Awake>m__2F () (at
Assets/Scripts/Localization/LocalizationLoader.cs:85)
ProjectPorcupine.Localization.LocalizationDownloader.OnDownloadLocalizationComplete
(System.Action onLocalizationDownloadedCallback) (at
Assets/Scripts/Localization/LocalizationDownloader.cs:267)
ProjectPorcupine.Localization.LocalizationDownloader+<DownloadLocalizationFromWeb>c__IteratorC.MoveNext
() (at Assets/Scripts/Localization/LocalizationDownloader.cs:143)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr
returnValueAddress) (at
C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
```